discord-config {
  token = ${TOKEN}
  postgres-password = ${POSTGRES_PASSWORD}
  postgres-host = ${POSTGRES_HOST}
  localapi-host = ${TIBIADATA_HOST}
  avatar-url = "https://raw.githubusercontent.com/Leo32onGIT/tibia-bot-resources/main/Violent%20Bot.png"
  fullbless-avatar-url = "https://raw.githubusercontent.com/Leo32onGIT/tibia-bot-resources/main/Amulet%20of%20Loss.png"
  namechange-thumbnail = "https://raw.githubusercontent.com/Leo32onGIT/tibia-bot-resources/main/namechange.png"
  guild-leave-thumbnail = "https://raw.githubusercontent.com/Leo32onGIT/tibia-bot-resources/main/guildleaveyellow.png"
  guild-swap-thumbnail-grey = "https://raw.githubusercontent.com/Leo32onGIT/tibia-bot-resources/main/guildswapgrey.png"
  guild-swap-thumbnail-red = "https://raw.githubusercontent.com/Leo32onGIT/tibia-bot-resources/main/guildswapred.png"
  guild-swap-thumbnail-green = "https://raw.githubusercontent.com/Leo32onGIT/tibia-bot-resources/main/guildswapgreen.png"
  guild-join-thumbnail-grey = "https://raw.githubusercontent.com/Leo32onGIT/tibia-bot-resources/main/guildjoingrey.png"
  guild-join-thumbnail-red = "https://raw.githubusercontent.com/Leo32onGIT/tibia-bot-resources/main/guildjoinred.png"
  guild-join-thumbnail-green = "https://raw.githubusercontent.com/Leo32onGIT/tibia-bot-resources/main/guildjoingreen.png"

  // Custom Emojis
  nemesis-emoji = "<:skull:>"
  archfoe-emoji = "<:smiling_imp:>"
  bane-emoji = "<:jack_o_lantern:>"
  summon-emoji = "<:squid:>"
  allyguild-emoji = "<:bee:>"
  otherguild-emoji = "<:snail:>"
  enemyguild-emoji = "<:crocodile:>"
  ally-emoji = "<:dog:>"
  enemy-emoji = "<:fly:>"
  neutral-emoji = "<:chicken:>"
  mk-emoji = "<:boxing_glove:>"
  zelos-emoji = "<:crown:>"
  library-emoji = "<:books:>"
  hod-emoji = "<:mirror_ball:>"
  feru-emoji = "<:man_mage:>"
  cube-emoji = "<:game_die:>"
  svar-green-emoji = "<:third_place:>"
  svar-scrapper-emoji = "<:second_place:>"
  svar-warlord-emoji = "<:first_place:>"
  inq-emoji = "<:japanese_ogre:>"
  kilmaresh-emoji = "<:hindu_temple:>"
  exiva-emoji = "<:speaking_head:>"
  indent-emoji = "<:kite:>"
  levelup-emoji = "<:star2:>"
  desire-emoji = "<:rosette:>"
  covet-emoji = "<:folding_hand_fan:>"
  primal-emoji = "<:bamboo:>"
  hazard-emoji = "<:sponge:>"
  boosted-boss-emoji = "<:mahjong:>"
  boosted-creature-emoji = "<:joker:>"
  yes-emoji = "<:white_check_mark:>"
  no-emoji = "<:x:>"
  letter-emoji = "<:love_letter:>"
  gold-emoji = "<:coin:>"
  boss-emoji = "<:space_invader:>"
  creature-emoji = "<:hatching_chick:>"
  torch-on-emoji = "<:full_moon_with_face:>"
  torch-off-emoji = "<:new_moon_with_face:>"
  satchel-emoji = "<:briefcafe:>"
  tcstack-emoji = "<:moneybag:>"
  message-delay-ms = 1350
  batch-size = 20
  batch-delay-ms = 2000
}
